Update UI:
google/testrun pull request #179
Opened 2023-11-09 13:43 UTC by sofyakurilova

linters+prettier added; unused files removed

2023-11-09 16:01 UTC, jboddey requested changes

2023-11-10 10:44 UTC, sofyakurilova commented on modules/ui/src/app/app-routing.module.ts
> -import { HashLocationStrategy, LocationStrategy } from '@angular/common';
{ useHash: true } do the same thing on line 48

2023-11-10 10:47 UTC, sofyakurilova commented on modules/ui/angular.json
> +            "outputPath": "dist/test-run-ui",
Sure

2023-11-10 15:17 UTC, jboddey approved these changes

2023-11-10 15:18 UTC, jboddey commented
Just awaiting CLA. Thanks @sofyakurilova

2023-12-05 11:37 UTC, jboddey commented
Closing this PR for now. The UI will be updated in another PR.

2023-12-05 11:37 UTC, closed without merging