Merge release v1.1.2 into dev
google/testrun pull request #274
Opened 2024-02-15 11:22 UTC by jboddey

2024-02-19 09:51 UTC, jboddey commented
Requires merge conflicts in UI

2024-02-20 14:20 UTC, jboddey commented
@sofyakurilova could you resolve the merge conflicts within the UI code for this PR?

2024-02-21 16:21 UTC, OlgaMardvilko requested changes
Please check how the conflicts are resolved.
There are a lot of issues related to resolving conflicts. 
It should be re-worked.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app-routing.module.ts
> +>>>>>>> dev
@sofyakurilova,
Please check how the conflicts are resolved.
We should re-work it.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app-routing.module.ts
> +>>>>>>> dev
Please resolve the conflicts.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app-routing.module.ts
> +>>>>>>> dev
The same: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.html
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.html
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.html
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.html
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.html
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.scss
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-21 16:21 UTC, OlgaMardvilko commented on modules/ui/src/app/app.component.spec.ts
> +>>>>>>> dev
The same here: Please check how the conflicts are resolved.

2024-02-22 12:00 UTC, OlgaMardvilko requested changes

2024-02-22 12:00 UTC, OlgaMardvilko commented on modules/ui/src/app/services/state.service.ts
> +}
I don't think we need to push this changes to dev as we didn't do anything related to this on the release v1.1.2. So, the dev branch has more correct last changes.
Let discuss.

2024-02-22 12:31 UTC, OlgaMardvilko approved these changes

2024-02-22 16:28 UTC, merged