Save new risk profile
google/testrun pull request #533
Opened 2024-06-21 08:30 UTC by sofyakurilova

![AYDCRSNNWMwqqJU](https://github.com/google/testrun/assets/22660354/22149c9e-0d42-4746-968c-5615f1458ddf)

Video after changes
http://screencast/cast/NjEzNjc0MDQxNzg5NjQ0OHxmOTZhOTNmOS1lZg

2024-06-21 12:25 UTC, jboddey requested changes
If the user is selecting 'Save Profile', the JSON request should include a top level field of 'status' with the value of 'Valid' to indicate to Testrun this is a final risk assessment. A missing status field indicates that it is a draft.

2024-06-26 00:03 UTC, jhughesbiot approved these changes

2024-06-26 07:17 UTC, OlgaMardvilko approved these changes

2024-06-26 12:07 UTC, jboddey approved these changes

2024-06-26 12:08 UTC, merged