Update delete device endpoint
google/testrun pull request #729
Opened 2024-08-29 14:44 UTC by MariusBaldovin

Updated the delete device endpoint to respond 404 instead of 500 if the report is not found.

Updated two tests for delete device endpoint to test 404 response (test_delete_report_no_report and test_delete_report_no_device).

2024-09-03 13:30 UTC, jboddey requested changes

2024-09-03 13:30 UTC, jboddey commented on testing/api/devices/device_2.json
> +        ],
Can you fix this formatting?

2024-09-03 14:17 UTC, MariusBaldovin commented on testing/api/devices/device_2.json
> +        ],
Solved

2024-09-05 14:31 UTC, jboddey requested changes

2024-09-05 14:31 UTC, jboddey commented on testing/api/devices/device_1.json
> +  "status": "Valid",
The status field should not be passed into the API. Only the backend will determine whether it is valid or not.

2024-09-05 14:31 UTC, jboddey commented on testing/api/devices/device_2.json
> +  "status": "Valid",
Same with this one

2024-09-05 15:04 UTC, jboddey approved these changes

2024-09-05 15:15 UTC, merged